name: Deploy to Existing Azure App

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

env:
  AZURE_WEBAPP_NAME: 'INNIAPP'
  AZURE_RESOURCE_GROUP: 'INNIT-RG'
  NODE_VERSION: '22.x'

jobs:
  test:
    runs-on: windows-latest
    name: Run Tests on Windows

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'

    - name: Install dependencies
      run: npm install

    - name: Run tests
      run: npm test

  deploy:
    runs-on: windows-latest
    name: Deploy to Azure App Service
    needs: test
    if: github.ref == 'refs/heads/main'

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'

    - name: Install dependencies
      run: npm install

    - name: Build application
      run: npm run build || echo "No build script defined"

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        resource-group: ${{ env.AZURE_RESOURCE_GROUP }}
        publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}

    - name: Verify Deployment
      run: |
        echo "🚀 Deployment completed!"
        echo "🌐 Your app is live at: https://${{ env.AZURE_WEBAPP_NAME }}.azurewebsites.net"
        echo "📊 Check logs at: https://portal.azure.com/#view/WebsitesExtension/WebAppBlade/resourceId/%2Fsubscriptions%2F7dd2559f-e860-4d00-9273-66be1bbfdc41%2FresourceGroups%2F${{ env.AZURE_RESOURCE_GROUP }}%2Fproviders%2FMicrosoft.Web%2Fsites%2F${{ env.AZURE_WEBAPP_NAME }}/logStream"
